apiVersion: apps/v1
kind: Deployment

metadata:
  name: static-site-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: static-site

  template:
    metadata:
      labels:
        app: static-site

    spec:
      containers:
        - name: static-site
          image: my-new-erp-site:v3
          imagePullPolicy: Never

          ports:
            - containerPort: 80